### ISSUE TITLE
Q: Would there be any major improvements for using a 6.25 MHz crystal?

### ISSUE THREAD

**Issue by cbmeeks** [jacgoudsmit/L-Star#1]
I know timing is tight.  But, how would running the Propeller at 6.25 MHz (25 MIPS) enhance the emulation?  Assuming there would be any enhancements at all.

Do you think the 65C02 could be pushed closer to 2 MHz?

I hope to build this really soon.  :-)

From what I understand, the real limitations here are the pin counts and RAM.

Anyway, thanks for such a great project!!!

**Comment by cbmeeks** [comment]
Sorry, I didn't see where you explicitly talked about this in the clock source.  Feel free to close this.  

Thanks!

**Comment by jacgoudsmit** [comment]
Hi cbmeeks.

While I was developing the Propeddle and L-Star, I was hoping I could make the 65(c)02 run faster than 1MHz, but there were several things that slowed things down, as compared to a (hypothetical) electronic solution instead of a sequential (programmed) solution.

For one thing, the Propeller only lets you read all the 32 pins at once. It doesn't allow a subset of the pins to be read. For this particular project, it would be great if I could use one single instruction to read the address bus or the data bus, without the need to shift/rotate the bits and/or mask them with a bitmask. That would save at least two instructions per 6502 cycle which is more than 10%.

Another problem is that it's almost unavoidable to have at least one hub instruction in the loop, and hub instructions take at least 8 Propeller cycles in the best case, or up to 23 cycles in the worst case. It took me a long time to design the original main loop of Propeddle in such a way that it would finish on time for the next 6502 cycle because of this.

If you want to run the 6502 faster while bitbanging it with a Propeller, you can probably do so if you add more electronics. My purpose with Propeddle and L-Star was to provide a flexible platform that could emulate many 1MHz 6502 systems (or could be used to design your own, to some extent). But if you want to use my ideas for something more specific, you can. For example, the Superboard III computer by Vince Briel at brielcomputers.com uses many of my ideas, but has an extenal address decoder to re-code the four address bus lines A15-A12 into three "virtual" address lines VA14-VA12 which made the logic for the Propeller firmware a little simpler and saved an I/O pin. If you want to use a separate Propeller just for video, for example, you can save a lot of pins too, by using an external address decoder. You could even make a system where the Propeller is sort of a GPU: just "send" it a command to draw (say) a circle and it does it without letting the 6502 wait, and such a system would only need 10 pins to interface with the 6502: a Chip Enable of sorts (with an external address decoder), the R/~W line and 8 data bus lines.

And you could do something that many 6502 systems from the 1980s did: run the 6502 on 2MHz or even faster for access to memory (using fast SRAM and 74F or 74AC address decoding logic for example) and slow the clock down or drop the RDY line to generate wait states when something needs to be done by the Propeller or some other slow peripherals.

Good luck!

**Comment by cbmeeks** [comment]
Thanks for the great information!

Haha...I've come to a similar conclusion.  Bottom line is that if you want more than 2MHz then you need external logic.  Either an entire Propeller running all 8 COGS to address memory (and that's still debatable) or discrete logic (or CPLD/FPGA) to handle address decoding.

I'm more than likely going to use an entire Propeller for video (and maybe audio) and have the CPU pass it commands.  The TMS9918 worked this way.  Many people hated that.  And for good reason.  You have to burn cycles to send a command and then more cycles to send address/data bytes.  A lot more work than a simple LDA #$10; STA $D000.

Of course you can do things to help out like having commands that allow paging and serializing bytes in so that consecutive bytes are just data bytes.  Very little overhead that way (TMS9918 also did this).

I'm brainstorming many ideas.  One idea is to have a "blitter" using the Propeller.  The 65C02 could send it some blitter commands and then the Propeller could move large amounts of RAM around the display memory, etc.

Effectively, it would be a sort of "copper list".  :-)

Oh, BTW, the way you bootstrap the 65C02 is genius.  Using the built in program counter of the 65C02 to save address line pins...cheating!!  But brilliant.  :-D

**Comment by jacgoudsmit** [comment]
The bootstrapping method was Dennis Ferron's idea. In his "Prop-6502 laptop" project he used NOP instructions but those are 1-byte, 2 cycles so the address only increases once every other clock pulse, I improved it by using CMP immediate, which is a 2 byte, 2 cycle instruction so the download (or upload which is not implemented yet but should be pretty trivial) goes twice as fast.

Dennis used the Reset vector to download the bootstrap code, but I use NMI. The advantages are that I can do an upload or download (sort of a DMA by cheating operation) while the system is running (e.g. to emulate a floppy disk, to "insert a cartridge", or to implement a hibernate-and-resume by reading/writing from/to EEPROM). The NMI combined with the RTI instruction fixes the problem that the flags are destroyed by the repeated CMP instruction. Also, using NMI and keeping the NMI input low (it's edge-triggered) makes it impossible for other hardware to interrupt the process. 

On the other hand, forcing an interrupt by executing a BRK instruction (and letting the Propeller check for the IRQ vector fetch) also gives an opportunity to do automatic downloads/uploads from the Propeller.
