### ISSUE TITLE
Constantly resetting...

### ISSUE THREAD

**Issue by cbmeeks** [jacgoudsmit/L-Star#2]
I've wired this up to a breadboard.  So far, I just have a Propeller and a 65C02 wired up.

I have tested the Propeller with a blinky demo and it seems to be stable.

When wire up the 65C02, it displays:

> L-STAR (c) 2014 JAC GOUDSMIT
> HUB RAM BYTES:

And it just repeats that over and over.  I am using the built-in Propeller tools serial terminal at 115200, echo on.

I've also connected the TV out and see the screen blinking.

I'm pretty sure I have proper decoupling caps on everything, getting 3.2xx volts at the 65C02.  Using a benchtop power supply.

Using a 5 MHz crystal.

Any ideas?

Thanks

**Comment by jacgoudsmit** [comment]
I've seen this before; I think it happens when you don't have a Prop Plug connected. I think the schematic is missing a couple of pull-up resistors for P31 and Reset (propeller) so when you disconnect the Prop plug, those lines start floating and oscillating and catching interference and other nasty stuff.

If you add two 10K resistors -- one between 3.3V and P31, and one between 3.3V and the Reset pin on the propeller -- or leave the Prop Plug connected, the problem should go away. I think you can even leave the Prop plug connected with no USB connection.

Let me know if that works!

===Jac

**Comment by cbmeeks** [comment]
Thanks for the quick reply.

Unfortunately, I've tried it with and without the PropPlug and it does the same thing either way.

Also, I need the PropPlug for the serial terminal.  :-)

I have a 10k pullup on P29 as per the schematics in the Propeller manual.  Plus, other spin programs work just fine.

**Comment by jacgoudsmit** [comment]
Hmmm... 

To check if it's a hardware problem or a software problem, try inserting this before the call to clock.Init in Apple1.spin (which should be the top level file).

``` spin
  repeat
    i:=0
```

This should send the main cog into an infinite loop and you should see the entire message including the "16384" on the serial port and on the monitor. After that, nothing should happen. If it still keeps resetting, it's most likely a hardware problem, e.g. interference between the serial port or video output to the reset line, or a power level that sags too much once the program gets busy (you have the Propeller BOE pin grounded, right?)

If that works okay, move the `repeat i:=0` instruction below the clock.init call, then further down etc.

You may also want to try running the 65C02 at a lower frequency, to see if it makes a difference. Simply change the clock.init call parameter to another value. You can even change the clock module so it doesn't call freq.Synth, and then control the hw#PIN_CLK0 output pin some other way, e.g. with a toggle switch, or from the serial port. The 65C02 is fully static so you can run it as slowly as you want. With a 5MHz crystal, you can run it up to 1MHz otherwise some of the helper cogs may not be able to keep up, but lower speeds are always okay.

Another thing to try is to delete the video module (comment out all references to the "tv" object in SerKbd1TV.spin). In a similar way you can delete the keyboard module (remove all references to kbd in the SerKbd1TV.spin file). This might give you some idea where any hardware problems are coming from.

Let me know if any of this helps...

**Comment by cbmeeks** [comment]
It's working!

OK, it was a hardware problem.  My "monster" breadboard that I built was dropping too much power.  I moved the bench power leads closer to the actual circuit and now I get a stable image. 

Sweet!

My scope is now showing a good solid 1.000MHz signal with an occasional drop to 960KHz.  But that's probably due to interference, breadboard, etc.

Thanks!

Now, how do I use the Woz monitor?  lol
Or basic?

**Comment by cbmeeks** [comment]
Never mind.  I figured it out.  :-)

It's totally working now.

Had to `3C00 R` and that jumped to BASIC.

AWESOME!!

Probably going to have a board made!  Do you have any extras to sell?

Thanks!

**Comment by jacgoudsmit** [comment]
Great! Good to hear you got it working.

I think I have one unpopulated PCB for L-Star, I'll send you an email.

For those reading along: You can order PCB's [here](https://oshpark.com/shared_projects/ATxyrTo7). A list of parts is [here](https://www.mouser.com/ProjectManager/ProjectDetail.aspx?ProjectGUID=144CCFEE-70F9-44B8-83F5-9934C3685E55). NOTE: the OSHPark and Mouser files are based on the [initial release](https://github.com/jacgoudsmit/L-Star/releases/tag/0.1); I've made several minor changes to the hardware design since then, but the latest software should still work.

The BOM on mouser.com doesn't include a power supply, keyboard, monitor or Prop Plug. You will also need a computer running the Parallax Propeller Tool to build the software. NOTE: There are currently no build instructions but those who have experience with soldering should be able to put this together pretty easily.

**Comment by cbmeeks** [comment]
Great!

Have you ever used http://www.pcbway.com for PCB's?

I love the purple look of OSH Park but PCB appears to be even cheaper (coming from China).

Bil Herd uses them according to his YouTube video.

Anyway, thanks for such an awesome project.  I've been trying to solder up a small protoboard for this but all of the wires are really a drag to solder.  

Thanks!
